name: C-Build-Test

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run : |
          sudo apt-get -y install sdcc
          sudo apt-get -y install make
          sudo apt-get -y install cmake
      - name: GCC build and run
        run : |
          mkdir ./build
          cd ./build
          cmake ..
          make
          ./cmake_test
      - name: GCC clean build
        run : rm -rf ./build/*
      - name: SDCC build
        run :  |
          cd ./build
          cmake -DCMAKE_TOOLCHAIN_FILE=../toolchain-sdcc.cmake -DMODE_SDCC=1 ..
          make
      - name: SDCC clean build
        run : rm -rf ./build/*
