name: C-Build-Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: GCC build source code
        run : gcc -w ./*.c -o test
      - name: GCC run source code
        run : ./test
      - name: GCC clean build
        run : rm -f ./test
      - name: SDCC install
        run : sudo apt-get -y install sdcc
      - name: SDCC version
        run : sdcc --version
      - name: SDCC compile
        run : sdcc ./test.c -o test
      - name: SDCC clean build
        run : rm -f ./test
