name: C-Build-Test

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: GCC build source code
        run : gcc -w ./*.c -o test
      - name: GCC run source code
        run : ./test
      - name: GCC clean build
        run : rm -f ./test
      - name: SDCC install
        run : sudo apt-get -y install sdcc
      - name: SDCC version
        run : sdcc --version
      - name: SDCC compile
        run : |
          sdcc --model-large --stack-auto -c modbus_rtu_base.c
          sdcc --model-large --stack-auto -c modbus_rtu_slave.c modbus_rtu_base.rel
          sdcc --model-large --stack-auto -c modbus_rtu_master.c modbus_rtu_base.rel
          sdcc --model-large --stack-auto -c test.c
          sdcc --model-large test.rel modbus_rtu_base.rel modbus_rtu_slave.rel modbus_rtu_master.rel
      - name: SDCC clean build
        run : rm -f *.asm *.lk *ihx *.lst *.rel *.rst *.sym *.map *.mem
